name: binder-py-eddy-exploration
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cartopy
  - holoviews>=1.14
  - geoviews>=1.9
  - panel>=0.11
  - datashader>=0.12
  - geopandas>=0.9.0
  - pip:
    - -r requirements.txt
    - pyeddytrackersample
    - pyeddytracker
    - .
    
